### ISSUE TITLE
1.8 stable won't connect

### ISSUE THREAD

**Issue by prophoto** [symless/synergy#5539]
I have Windows 10 x64 server running 1.8.2 stable, client is macOS Sierra 1.8.2 stable. Client always says "WARNING: failed to connect to server: Timed out"

HELP!

**Comment by prophoto** [comment]
More info...tried reversing it, ran Mac as server and Win10 as client, connected immediately without issue.

Also this error in log
ERROR: could not get session id for process id 5524 on server.

**Comment by prophoto** [comment]
And another error

ERROR: failed to get desktop path, no drop target available, error=2

**Comment by prophoto** [comment]
Got it running with Win10 as server, had to disable elevate mode. Definitely a bug here somewhere.

**Comment by prophoto** [comment]
Also auto config worked fine when I had the Mac as the server, it prompted me to add the PC as a client with the layout config box. That box does not pop up when attempting auto config with the PC as the server.

**Comment by XinyuHou** [comment]
Closed as this is a support ticket and the problem has been solved.

**Comment by prophoto** [comment]
> Closed as this is a support ticket and the problem has been solved.

Explain?

**Comment by iures** [comment]
Just bought and still have the same issue.

**Comment by dddw** [comment]
same here... trying with Mac OsX Sierra as server and Debian as client... no firewalls or anything else... keep getting timeouts. Same if I try to telnet from my debian client machine to mac server machine to the 24800 port. Currently have two different releases, will check with both on latest releases. If problem persists I'll reopen a new issue.
